name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.2

      # - name: Build binary
      #   run: go build -o ${{ github.event.repository.name }} ./cmd/${{ github.event.repository.name }}

      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ${{ github.event.repository.name }}
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binaries for multiple platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/${{ github.event.repository.name }}-linux ./cmd/${{ github.event.repository.name }}
          GOOS=darwin GOARCH=amd64 go build -o dist/${{ github.event.repository.name }}-mac-intel ./cmd/${{ github.event.repository.name }}
          GOOS=darwin GOARCH=arm64 go build -o dist/${{ github.event.repository.name }}-mac ./cmd/${{ github.event.repository.name }}
          GOOS=windows GOARCH=amd64 go build -o dist/${{ github.event.repository.name }}-windows.exe ./cmd/${{ github.event.repository.name }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          token: ${{ secrets.GITHUB_TOKEN }}

